### ISSUE TITLE
Is it possible to suggest additional features?

### ISSUE THREAD

**Issue by laterre39** [oylsister/SM-GunMenu#1]
Hello, I am running a zombie server.

Server crashes occasionally due to a recent Dropweapon issue with ZR.
Does that plugin fix zmarket weapon drop issues?

I'm also wondering if it's possible to limit the number of weapon purchases based on the total number of players in each round.

ex) If there are 10 players, you can only buy 2 negevs.

Thanks for making a great plugin. Please reply when you have time.

**Comment by oylsister** [comment]
Sm-GunMenu is designed to replace the zmarket in the first place, Meaning you can disable zmarket completely. (exclude weapon module) 

for limitation I suggest you to use already existed api "GunMenu_OnClientPurchase" to prevent purchasing.
